name: face_tracker_viewer
description: Desktop viewer for RTP stream from Raspberry Pi face tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_vlc: ^0.4.0
  http: ^1.1.0
  provider: ^6.1.1
  window_manager: ^0.3.7
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  audio_video_progress_bar: ^2.0.3
